# Generated by Django 5.0.14 on 2026-07-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('icon', models.CharField(choices=[('bi-receipt', 'Receipt'), ('bi-cash-coin', 'Cash'), ('bi-building', 'Building'), ('bi-card-checklist', 'Checklist'), ('bi-journal-text', 'Journal'), ('bi-search', 'Audit / Search'), ('bi-shield-check', 'Compliance'), ('bi-people', 'Consultancy')], default='bi-receipt', max_length=40)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('fee_note', models.CharField(blank=True, help_text="e.g. 'Starting from PKR 5,000'", max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
