# Generated by Django 6.0.6 on 2026-07-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Reply from staff, visible to the client on their account'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
